syntax = "proto3";

package media.v1;

service MediaService {
    rpc Upload (stream UploadRequest) returns (UploadResponse);
    rpc Delete (DeleteRequest) returns (DeleteResponse);
}

message UploadRequest {
    oneof payload {
        UploadMetadata metadata = 1;
        bytes chunk_data = 2;
    }
}

message UploadMetadata {
    string file_name = 1;
    string folder = 2;
    string content_type = 3;
}

message UploadResponse {
    string key = 1;
    string url = 2;
}

message DeleteRequest {
    string key = 1;
}

message DeleteResponse {
    bool ok = 1;
}